# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('passengerid', models.IntegerField(db_column='PassengerId', primary_key=True, serialize=False)),
                ('survived', models.CharField(db_column='Survived', max_length=1)),
                ('pclass', models.CharField(blank=True, db_column='Pclass', max_length=1, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=250, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=10, null=True)),
                ('age', models.DecimalField(blank=True, db_column='Age', decimal_places=2, max_digits=5, null=True)),
                ('sibsp', models.IntegerField(blank=True, db_column='SibSp', null=True)),
                ('parch', models.IntegerField(blank=True, db_column='Parch', null=True)),
                ('ticket', models.CharField(blank=True, db_column='Ticket', max_length=50, null=True)),
                ('fare', models.DecimalField(blank=True, db_column='Fare', decimal_places=4, max_digits=10, null=True)),
                ('cabin', models.CharField(blank=True, db_column='Cabin', max_length=50, null=True)),
                ('embarked', models.CharField(blank=True, db_column='Embarked', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Training',
            },
        ),
    ]
